const CONFIG={whatsapp:'https://wa.me/6289500000000',instagram:'https://instagram.com/inhistoria.id',tiktok:'https://tiktok.com/@inhistoria.id'};
const heroPhotos=['assets/hero-1.jpg','assets/hero-2.png','assets/hero-3.jpg'];
const portfolioPhotos=[
 {src:'assets/campus-1.jpg',title:'UIN SAIZU',subtitle:'PURWOKERTO'},
 {src:'assets/campus-2.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'},
 {src:'assets/campus-3.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'},
 {src:'assets/campus-4.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'}
];
const closingPhotos=['assets/closing-1.jpg','assets/campus-3.jpg','assets/hero-3.jpg'];
const lensPortfolio=[
 {src:'assets/through/card-01.jpg',name:'UIN SAIZU',slug:'uin-saizu',meta:'Purwokerto'},
 {src:'assets/through/card-02.jpg',name:'UNIVERSITAS JENDERAL SOEDIRMAN',slug:'universitas-jenderal-soedirman',meta:'Purwokerto'},
 {src:'assets/through/card-03.jpg',name:'UIN SAIZU',slug:'uin-saizu-2',meta:'Purwokerto'},
 {src:'assets/through/card-04.jpg',name:'UNIVERSITAS JENDERAL SOEDIRMAN',slug:'universitas-jenderal-soedirman-2',meta:'Purwokerto'},
 {src:'assets/through/card-05.jpg',name:'UNIVERSITAS JENDERAL SOEDIRMAN',slug:'universitas-jenderal-soedirman-3',meta:'Purwokerto'},
 {src:'assets/through/card-06.jpg',name:'UIN SAIZU',slug:'uin-saizu-3',meta:'Purwokerto'}
];
const nav=[['Home','/'],['Through Our Lens','/through-our-lens'],['Portfolio','/portfolio'],['Package','/package'],['Contact','/contact'],['Booking','/booking']];
let heroIndex=0,closingIndex=0,portfolioOffset=0;
function navigate(path){history.pushState({},'',path);render();scrollTo({top:0,behavior:'smooth'})}
function waIcon(){return `<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M19.11 17.23c-.27-.14-1.6-.79-1.85-.88-.25-.09-.43-.14-.61.14-.18.27-.7.88-.86 1.06-.16.18-.32.2-.59.07-.27-.14-1.13-.42-2.15-1.33-.79-.7-1.33-1.57-1.49-1.84-.16-.27-.02-.42.12-.56.12-.12.27-.32.41-.48.14-.16.18-.27.27-.45.09-.18.05-.34-.02-.48-.07-.14-.61-1.47-.84-2.01-.22-.53-.45-.46-.61-.47h-.52c-.18 0-.48.07-.73.34-.25.27-.95.93-.95 2.26s.98 2.62 1.11 2.8c.14.18 1.93 2.95 4.68 4.14.65.28 1.16.45 1.56.58.66.21 1.27.18 1.75.11.53-.08 1.6-.65 1.83-1.28.23-.63.23-1.17.16-1.28-.07-.11-.25-.18-.52-.32Z"/><path fill="currentColor" d="M16 3.2A12.77 12.77 0 0 0 5.16 22.7L3.2 28.8l6.3-1.92A12.8 12.8 0 1 0 16 3.2Zm0 23.25c-2.01 0-3.98-.54-5.7-1.56l-.41-.24-3.74 1.14 1.15-3.64-.27-.42A10.55 10.55 0 1 1 16 26.45Z"/></svg>`}
function header(){return `<header class="site-nav" id="siteNav"><button class="brand-button" data-route="/" aria-label="Back to home"><img src="assets/logo.png" alt="InHistoria"></button><nav aria-label="Primary navigation">${nav.map(([label,href])=>`<button data-route="${href}">${label}</button>`).join('')}</nav></header><div class="nav-trigger" id="navTrigger"></div>`}
function hero(){const cols=[0,1,2].map(i=>heroPhotos[(heroIndex+i)%heroPhotos.length]);return `<section class="hero"><div class="hero-grid">${cols.map((src,i)=>`<div class="hero-panel"><img src="${src}?v=${heroIndex}-${i}" alt="InHistoria photography"></div>`).join('')}</div><div class="hero-overlay"></div><div class="hero-copy"><span class="eyebrow">INHISTORIA.GRAD</span><h1>Eternal Moment</h1><p>everything that was once close is now eternal in<br>a frame that doesn't go away</p><div class="hero-actions"><button class="button button-light" data-route="/portfolio">Explore Our Work</button><button class="button button-outline" data-route="/booking">Booking Now</button></div></div></section>`}
function portfolio(){const cards=[0,1,2,3].map(i=>portfolioPhotos[(i+portfolioOffset)%portfolioPhotos.length]);return `<section class="quote-strip"><p>A glimpse into the stories we've had the chance to capture.</p></section><section class="portfolio-preview"><div class="portfolio-track">${cards.map(item=>`<article class="portfolio-card" data-route="/portfolio#${encodeURIComponent(item.title+'-'+item.subtitle)}"><img src="${item.src}" alt="${item.title} ${item.subtitle}"><div class="card-gradient"></div><div class="card-copy"><strong>${item.title}</strong><span>${item.subtitle}</span></div></article>`).join('')}</div><button class="slider-arrow left" data-slider="-1" aria-label="Previous work">‹</button><button class="slider-arrow right" data-slider="1" aria-label="Next work">›</button><button class="all-work" data-route="/portfolio">Explore All Work <span>→</span></button></section>`}
function footer(){return `<footer class="site-footer"><div class="footer-main"><button class="footer-brand" id="backTop"><img src="assets/logo.png" alt="InHistoria"></button><div class="socials"><a href="${CONFIG.instagram}" target="_blank" rel="noreferrer" aria-label="Instagram">◎</a><a href="${CONFIG.tiktok}" target="_blank" rel="noreferrer" aria-label="TikTok">♪</a><a href="${CONFIG.whatsapp}" target="_blank" rel="noreferrer" aria-label="WhatsApp">${waIcon()}</a></div><div class="footer-navigation"><h3>Navigation</h3><div>${nav.filter(x=>x[0]!=='Home').map(([label,href])=>`<button data-route="${href}">${label}</button>`).join('')}</div></div></div><div class="copyright">© 2026 InHistoria.grad. All rights reserved.</div></footer>`}
function home(){return `${hero()}${portfolio()}<section class="closing-image"><img class="crossfade-image" src="${closingPhotos[closingIndex]}?v=${closingIndex}" alt="InHistoria graduation photography"></section>${footer()}`}
function throughOurLens(){return `<main class="lens-page"><section class="lens-hero"><div class="lens-hero-bg"></div><div class="lens-hero-overlay"></div><div class="lens-copy"><h1>Through Our Lens</h1><p>We believe photography is about more than simply preserving a moment. It is about capturing the warmth, the quiet emotions, and the beauty found in between.</p></div></section><section class="lens-work"><div class="lens-work-grid">${lensPortfolio.map(item=>`<article class="lens-card" data-route="/portfolio#${item.slug}"><img src="${item.src}" alt="${item.name}"><div class="lens-card-overlay"></div><div class="lens-card-copy"><strong>${item.name}</strong><span>${item.meta}</span></div></article>`).join('')}</div><button class="lens-all-work" data-route="/portfolio">Explore All Work <span>→</span></button></section></main>`}
function placeholder(){const label=location.pathname.split('/').filter(Boolean)[0]?.replaceAll('-',' ')||'page';return `<section class="placeholder"><p>InHistoria</p><h1>${label}</h1><button class="button button-light" data-route="/">Back Home</button></section>`}
function render(){document.getElementById('app').innerHTML=header()+(location.pathname==='/'?home():location.pathname==='/through-our-lens'?throughOurLens():placeholder());document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.route)));const back=document.getElementById('backTop');if(back)back.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('[data-slider]').forEach(b=>b.onclick=()=>{portfolioOffset=(portfolioOffset+Number(b.dataset.slider)+portfolioPhotos.length)%portfolioPhotos.length;render()});const navEl=document.getElementById('siteNav');navEl.classList.toggle('is-visible',scrollY<40)}
render();
setInterval(()=>{if(location.pathname==='/'){heroIndex=(heroIndex+1)%heroPhotos.length;render()}},5500);
setInterval(()=>{if(location.pathname==='/'){closingIndex=(closingIndex+1)%closingPhotos.length;const el=document.querySelector('.crossfade-image');if(el){el.src=closingPhotos[closingIndex]+'?v='+closingIndex;el.classList.remove('crossfade-image');void el.offsetWidth;el.classList.add('crossfade-image')}}},6000);
let scrollTimer;window.addEventListener('mousemove',e=>{const navEl=document.getElementById('siteNav');if(navEl)navEl.classList.toggle('is-visible',e.clientY<120||scrollY<40)});window.addEventListener('scroll',()=>{const wa=document.getElementById('floatingWa');if(wa)wa.classList.add('is-scrolling');clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const wa2=document.getElementById('floatingWa');if(wa2)wa2.classList.remove('is-scrolling')},500)},{passive:true});document.addEventListener('mouseenter',e=>{if(e.target.id==='navTrigger'){const navEl=document.getElementById('siteNav');if(navEl)navEl.classList.add('is-visible')}},true);
