const CONFIG={whatsapp:'https://wa.me/6289500000000',instagram:'https://instagram.com/inhistoria.id',tiktok:'https://tiktok.com/@inhistoria.id'};
const heroPhotos=['assets/hero-1.jpg','assets/hero-2.png','assets/hero-3.jpg'];
const portfolioPhotos=[
 {src:'assets/campus-1.jpg',title:'UIN SAIZU',subtitle:'PURWOKERTO'},
 {src:'assets/campus-2.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'},
 {src:'assets/campus-3.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'},
 {src:'assets/campus-4.jpg',title:'UNIVERSITAS',subtitle:'JENDERAL SOEDIRMAN'}
];
const closingPhotos=['assets/closing-1.jpg','assets/campus-3.jpg','assets/hero-3.jpg'];
const nav=[['Home','/'],['Through Our Lens','/through-our-lens'],['Portfolio','/portfolio'],['Package','/package'],['Contact','/contact'],['Booking','/booking']];
let heroIndex=0,closingIndex=0,portfolioOffset=0;
function navigate(path){history.pushState({},'',path);render();scrollTo({top:0,behavior:'smooth'})}
function hero(){const cols=[0,1,2].map(i=>heroPhotos[(heroIndex+i)%heroPhotos.length]);return `<section class="hero"><div class="hero-grid">${cols.map((src,i)=>`<div class="hero-panel"><img src="${src}?v=${heroIndex}-${i}" alt="InHistoria photography"></div>`).join('')}</div><div class="hero-overlay"></div><div class="hero-copy"><span class="eyebrow">INHISTORIA.GRAD</span><h1>Eternal Moment</h1><p>everything that was once close is now eternal in<br>a frame that doesn't go away</p><div class="hero-actions"><button class="button button-light" data-route="/portfolio">Explore Our Work</button><button class="button button-outline" data-route="/booking">Booking Now</button></div></div></section>`}
function portfolio(){const cards=[0,1,2,3].map(i=>portfolioPhotos[(i+portfolioOffset)%portfolioPhotos.length]);return `<section class="quote-strip"><p>A glimpse into the stories we've had the chance to capture.</p></section><section class="portfolio-preview"><div class="portfolio-track">${cards.map(item=>`<article class="portfolio-card"><img src="${item.src}" alt="${item.title} ${item.subtitle}"><div class="card-gradient"></div><div class="card-copy"><strong>${item.title}</strong><span>${item.subtitle}</span></div></article>`).join('')}</div><button class="slider-arrow left" data-slider="-1" aria-label="Previous work">‹</button><button class="slider-arrow right" data-slider="1" aria-label="Next work">›</button><button class="all-work" data-route="/portfolio">Explore All Work <span>→</span></button></section>`}
function footer(){return `<footer class="site-footer"><div class="footer-main"><button class="footer-brand" id="backTop"><img src="assets/logo.png" alt="InHistoria"></button><div class="socials"><a href="${CONFIG.instagram}" target="_blank" rel="noreferrer" aria-label="Instagram">◎</a><a href="${CONFIG.tiktok}" target="_blank" rel="noreferrer" aria-label="TikTok">♪</a><a href="${CONFIG.whatsapp}" target="_blank" rel="noreferrer" aria-label="WhatsApp">◔</a></div><div class="footer-navigation"><h3>Navigation</h3><div>${nav.filter(x=>x[0]!=='Home').map(([label,href])=>`<button data-route="${href}">${label}</button>`).join('')}</div></div></div><div class="copyright">© 2026 InHistoria.grad. All rights reserved.</div></footer>`}
function home(){return `${hero()}${portfolio()}<section class="closing-image"><img class="crossfade-image" src="${closingPhotos[closingIndex]}?v=${closingIndex}" alt="InHistoria graduation photography"></section>${footer()}`}
function placeholder(){const label=location.pathname.split('/').filter(Boolean)[0]?.replaceAll('-',' ')||'page';return `<section class="placeholder"><p>InHistoria</p><h1>${label}</h1><button class="button button-light" data-route="/">Back Home</button></section>`}
function render(){document.getElementById('app').innerHTML=location.pathname==='/'?home():placeholder();document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.route)));const back=document.getElementById('backTop');if(back)back.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('[data-slider]').forEach(b=>b.onclick=()=>{portfolioOffset=(portfolioOffset+Number(b.dataset.slider)+portfolioPhotos.length)%portfolioPhotos.length;render()});}
render();
setInterval(()=>{if(location.pathname==='/'){heroIndex=(heroIndex+1)%heroPhotos.length;render()}},5500);
setInterval(()=>{if(location.pathname==='/'){closingIndex=(closingIndex+1)%closingPhotos.length;const el=document.querySelector('.crossfade-image');if(el){el.src=closingPhotos[closingIndex]+'?v='+closingIndex;el.classList.remove('crossfade-image');void el.offsetWidth;el.classList.add('crossfade-image')}}},6000);
const navEl=document.getElementById('siteNav');let scrollTimer;window.addEventListener('mousemove',e=>{navEl.classList.toggle('is-visible',e.clientY<120||scrollY<40)});window.addEventListener('scroll',()=>{document.getElementById('floatingWa').classList.add('is-scrolling');clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>document.getElementById('floatingWa').classList.remove('is-scrolling'),500)},{passive:true});document.getElementById('navTrigger').addEventListener('mouseenter',()=>navEl.classList.add('is-visible'));document.getElementById('floatingWa').href=CONFIG.whatsapp;
